# Generated by Django 4.0.4 on 2022-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountriesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries_languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('language_name', models.CharField(max_length=100)),
            ],
        ),
    ]
